MD032 = true
MD058 = true

[MD012]
maximum = 1

[MD013]
line_length = 80
code_blocks = false
tables = false
headings = false

[MD022]
lines_above = 1
lines_below = 1

[MD024]
siblings_only = true

[MD031]
list_items = false

[list-item-spacing]
checkBlanks = true
